#! /bin/bash

if [ -z "$GITHUB_USERID" ]; then
    echo "The environment variable GITHUB_USERID is not set."
    echo "Please set and re-run this script."
    exit 1
fi

if [ -z "$GITHUB_ACCESS_TOKEN" ]; then
    echo "The environment variable GITHUB_ACCESS_TOKEN is not set."
    echo "Please set and re-run this script."
    exit 1
fi

INVITES=/tmp/invites$$.txt
NUM_INVITES=1
while (( $NUM_INVITES > 0 )); do
    curl -s -u "$GITHUB_USERID":"$GITHUB_ACCESS_TOKEN" "https://api.github.com/user/repository_invitations?per_page=100" > $INVITES
    NUM_INVITES=$(jq '.[].repository.name' < $INVITES | wc -l)
    echo "Found $NUM_INVITES more invites"

    for id in $(jq '.[].id' < $INVITES); do
	echo -n "Attempting to accept invitation $id..."
	STATUS=$(curl -s -i -u "$GITHUB_USERID":"$GITHUB_ACCESS_TOKEN" -X PATCH "https://api.github.com/user/repository_invitations/$id" | grep "Status:")
	echo "$STATUS" | grep 204 > /dev/null
	if [ $? -eq 0 ]; then
            echo OK
	else
            echo FAIL
	fi
    done
done

rm /tmp/*$$*
