#! /bin/bash

if [ -z "$GITHUB_USERID" ]; then
    echo "The environment variable GITHUB_USERID is not set."
    echo "Please set and re-run this script."
    exit 1
fi

if [ -z "$GITHUB_ACCESS_TOKEN" ]; then
    echo "The environment variable GITHUB_ACCESS_TOKEN is not set."
    echo "Please set and re-run this script."
    exit 1
fi

NUM_INVITES_READ=1
PAGE=1
INVITES_BUFFER=invites$$.txt
ALL_INVITES=all-invites$$.txt
while (( $NUM_INVITES_READ > 0 )); do
    curl -s -u "$GITHUB_USERID":"$GITHUB_ACCESS_TOKEN" "https://api.github.com/user/repository_invitations?per_page=100&page=$PAGE" > $INVITES_BUFFER
    cat $INVITES_BUFFER >> $ALL_INVITES
    NUM_INVITES_READ=$(jq '.[].repository.name' < $INVITES_BUFFER | wc -l)
    echo "Found $NUM_INVITES_READ more invites"
    let PAGE++
done

for id in $(jq '.[].id' < $ALL_INVITES); do
    echo -n "Attempting to accept invitation $id..."
    STATUS=$(curl -s -i -u "$GITHUB_USERID":"$GITHUB_ACCESS_TOKEN" -X PATCH "https://api.github.com/user/repository_invitations/$id" | grep "Status:")
    echo "$STATUS" | grep 204 > /dev/null
    if [ $? -eq 0 ]; then
        echo OK
    else
        echo FAIL
    fi
done
